# Generated by Django 5.2.11 on 2026-02-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance', models.FloatField(default=0.0, help_text='Total route distance in km.')),
                ('estimated_time', models.FloatField(default=0.0, help_text='Estimated drive time in minutes.')),
                ('estimated_co2', models.FloatField(default=0.0, help_text='Estimated CO₂ emissions in kg.')),
                ('polyline', models.TextField(blank=True, default='', help_text='Encoded Google polyline.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveSmallIntegerField()),
                ('visited_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['stop_order'],
            },
        ),
    ]
