# Generated by Django 5.2.11 on 2026-02-23 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('containers', '0001_initial'),
        ('routes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routestop',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='containers.container'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.route'),
        ),
        migrations.AddField(
            model_name='route',
            name='containers',
            field=models.ManyToManyField(blank=True, related_name='routes', through='routes.RouteStop', to='containers.container'),
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'stop_order')},
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['driver', '-created_at'], name='routes_rout_driver__fb2097_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['status'], name='routes_rout_status_fbf2dd_idx'),
        ),
    ]
