# Generated by Django 5.2.11 on 2026-02-23 19:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='WGS-84 longitude/latitude point.', srid=4326)),
                ('fill_level', models.FloatField(default=0.0, help_text='Current fill level as percentage (0–100).')),
                ('waste_type', models.CharField(choices=[('general', 'General Waste'), ('recyclable', 'Recyclable'), ('organic', 'Organic'), ('hazardous', 'Hazardous'), ('electronic', 'Electronic')], default='general', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fill_history', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Containers',
                'ordering': ['-fill_level'],
                'indexes': [models.Index(fields=['fill_level'], name='containers__fill_le_6875d3_idx'), models.Index(fields=['waste_type'], name='containers__waste_t_c98734_idx')],
            },
        ),
    ]
